### ISSUE TITLE
Print statement not working when called within a function

### ISSUE THREAD

**Issue by kwbachman** [seanbachman/asa_lang#2]
In the following example, "Hello World 1 !" is output but the other print statements are not.

print("Hello World 1 !")
prt();

fn main() {
  print("Hello World 2 !")
  prt()
}

fn prt() {
  print("Hello World 3 !")
}

**Comment by seanbachman** [comment]
Incorrect syntax, statements are outside of main function. This used to be an issue though even with correct syntax but it is now resolved.

**Comment by seanbachman** [comment]
try running

fn main() {
    print("Hello World 2 !")
    prt()
}

fn prt() {
    print("Hello World 3 !")
}
